global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Currency API metrics - scrape all 4 replicas
  - job_name: "currency-api"
    static_configs:
      - targets: ["demo_currency_app-api-1:8000", "demo_currency_app-api-2:8000", "demo_currency_app-api-3:8000", "demo_currency_app-api-4:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s
    scheme: http

  # Nginx load balancer metrics
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s
    scheme: http

  # PostgreSQL database metrics
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http

  # Additional services can be added here as needed

  # cAdvisor container metrics (ARM64 compatible)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
